version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - db_network
      - nginx_network
    restart: unless-stopped

  meal_app:
    build: ./meal_api
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - DIET_URL=http://diet_api:5002
    networks:
      - db_network
      - nginx_network
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 2

  diet_api:
    build: ./diet_api
    ports:
      - 5002:5002
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    networks:
      - db_network
      - nginx_network
    restart: unless-stopped

  meal_api:
    image: nginx:latest
    volumes:
      - ./nginx/meals-nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5001:5001
    depends_on:
      - meal_app
    networks:
      - nginx_network
    restart: unless-stopped
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - meal_api
      - diet_api
    networks:
      - nginx_network
    restart: unless-stopped

volumes:
  db_data:

networks:
  db_network:
  nginx_network:
